language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest-cov
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - pytest --cov=app/

after_success:
- coveralls
